# Generated by Django 4.0.3 on 2022-03-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
