# Generated by Django 4.0.3 on 2022-03-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='site_link',
        ),
    ]
